### ISSUE TITLE
Typos in L10_RT and Multimedia.md

### ISSUE THREAD

**Issue by jenip13** [audrey617/CS6210-Advanced-Operating-Systems-Notes#3]
3. Novel Multimedia Apps
, so that we can take **timely** actions

5. Programming Model for Situation Awareness
 what is happening in the **environment** 

6. PTS Programming Model
and that way, there is **temporaral** causality 
that it is getting from all these **streams**. 

9. PTS Design Principles
 large scale distributed computation in which **channels** exist

10. Persistant Channel Architecture 
 that react to these get and **put** calls 
he heavy lifting that needs to be done during **run time**
triggers being passed from the **live** channel

**Comment by audrey617** [comment]
👍  Fixed.  Thanks!
