### ISSUE TITLE
8.1 LRVM 

### ISSUE THREAD

**Issue by jenip13** [audrey617/CS6210-Advanced-Operating-Systems-Notes#4]
4. RVM Primitives
 in memory versions of persistent data structures **represent**

5. RVM Primitives (cont)
as redo logs **in** the log segment. 

o ahead and apply these **redo logs** to the **external** segments and truncate the log.

9. Implementation
**end** transaction and the point at which the 
**reverse** displacements are helpful in traversing

10.
for each of the address **range** within that critical section, what is the new data that corresponds to the changes that have been made to that **range**
 on mapping and data segment **to** the subsystem that wants to use it.

**Comment by audrey617** [comment]
Fixed. Thanks!
