### ISSUE TITLE
RioVista

### ISSUE THREAD

**Issue by jenip13** [audrey617/CS6210-Advanced-Operating-Systems-Notes#6]
7. IPC Fundamental to System Services
on the local **area** network 

8. Bundling Distributed IPC and X Actions
 the IPC calls **are tagged** with transaction ID.
transaction, that is the root of the transaction **tree**

10. Distributed Transaction
node A, has to manage the transaction **trees** corresponding
to coordinator of the whole transaction **tree.**

11. Commit Initiated by Coordinator
it might ask for vote request on commuting. 

13. Quicksilver Conclusion 
bundle **in state** recover

**Comment by audrey617** [comment]
Fixed. Thanks!
